# Generated by Django 3.0.4 on 2020-04-07 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balance',
            old_name='amount_received',
            new_name='transfers',
        ),
    ]
