# Generated by Django 3.0.4 on 2020-04-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200407_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='transfers',
        ),
        migrations.AddField(
            model_name='balance',
            name='transfers',
            field=models.ManyToManyField(to='core.MoneyTransfer'),
        ),
    ]
